import type { Metadata } from 'next'
import { Noto_Sans_Display } from 'next/font/google'
import Provider from './provider'
import './globals.css'

const notoSansDisplay = Noto_Sans_Display({
    variable: '--font-noto-sans-display',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Lentera Cendekia',
    description: 'Generated by create next app',
    authors: [{ name: 'Lentera Cendekia' }, { name: 'LBB Lentera Cendekia' }],
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${notoSansDisplay.variable} antialiased`}>
                <Provider>{children}</Provider>
            </body>
        </html>
    )
}
